#!/usr/bin/env node
/**
 * code_boss — production single-file bundle. Generated by scripts/build.mjs.
 * Starts a local web UI on http://127.0.0.1:<PORT>/ and opens it in the
 * default browser. Talks to an OpenAI-compatible endpoint (api.genai.mil by
 * default). No npm deps. Node 20+ for built-in fetch.
 *
 * Usage:
 *   node code-boss.mjs            (opens the chat UI)
 *   PORT=18999 node code-boss.mjs (override the port)
 *
 * Edit the CONFIG constants below for your environment.
 */

// ====== CONFIG (edit these) ======
const API_KEY  = '';                                // bearer token
const BASE_URL = 'https://api.genai.mil/v1';        // OpenAI-compatible endpoint
const MODEL    = 'gemini-3.1-pro-preview';          // default model selected in the dropdown
const PORT     = Number(process.env.PORT ?? 18888); // local UI port
// ==================================

import { spawn } from 'node:child_process';
import { createInterface } from 'node:readline';
import { createServer } from 'node:http';
import { homedir } from 'node:os';
import { readFile as _readFile, writeFile as _writeFile, mkdir as _mkdir, stat as _stat, readdir as _readdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { randomUUID as _randomUUID } from 'node:crypto';
import path from 'node:path';
const readFile = _readFile, writeFile = _writeFile, mkdir = _mkdir, stat = _stat, readdir = _readdir;
const randomUUID = _randomUUID;


// ====== llm/openai-http.mjs ======
/**
 * Production OpenAI-compatible HTTP adapter — talks to api.genai.mil.
 *
 * Same surface as the dev adapter:
 *   const a = createHttpAdapter({ baseURL, apiKey })
 *   await a.complete(openaiRequest)
 *   for await (const chunk of a.completeStream(openaiRequest)) { ... }
 *
 * Production behaviours wired in here:
 *   - 401 with `unlock_url` → open the URL in the default browser, prompt the
 *     user to press Enter once they've unlocked in the browser, then retry
 *     once. The /user-ui/unlock/... endpoints are browser pages, not API
 *     endpoints — programmatic GET doesn't actually unlock the key.
 *   - 429 with Retry-After header or retry_after_seconds body → sleep, retry
 *     (max 3 attempts, exponential floor)
 *   - SSE streaming parsed into OpenAI ChatCompletionChunk async iterator
 *   - Bearer auth via Authorization header
 *   - Pass-through of unknown fields on assistant messages and tool_calls
 *     (Gemini 3 returns a `thought_signature` field that must round-trip
 *     verbatim to preserve reasoning across function calls). The adapter
 *     never strips fields; the agent loop must echo assistant messages back
 *     intact in subsequent requests.
 *
 * Diagnostics:
 *   - AGENT_DEBUG=1 logs every request's tool_call_ids (outbound) and the
 *     response's assistant.tool_calls[*].id + any non-OpenAI fields seen
 *     (thought_signature, encrypted_content, etc.) so we can verify ID
 *     round-tripping against api.genai.mil on the first real run.
 *
 * No npm deps. Node 18+ built-in fetch only.
 */


const DEFAULT_BASE_URL = 'https://api.genai.mil/v1';

// Standard Chrome install locations on Windows (per-user + per-machine).
const CHROME_PATHS_WIN = [
  (process.env.LOCALAPPDATA || '') + '\\Google\\Chrome\\Application\\chrome.exe',
  'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',
  'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe',
];
function findChromeWin() {
  for (const p of CHROME_PATHS_WIN) {
    try { if (p && existsSync(p)) return p; } catch {}
  }
  return null;
}

function openInBrowser(url) {
  // Prefer Chrome; fall back to the OS default if Chrome isn't installed.
  if (process.platform === 'win32') {
    const chrome = findChromeWin();
    if (chrome) {
      spawn(chrome, [url], { stdio: 'ignore', detached: true }).unref();
    } else {
      spawn('cmd', ['/c', 'start', '""', url], { stdio: 'ignore', detached: true, windowsHide: true }).unref();
    }
  } else if (process.platform === 'darwin') {
    spawn('open', ['-a', 'Google Chrome', url], { stdio: 'ignore', detached: true }).unref();
  } else {
    spawn('google-chrome', [url], { stdio: 'ignore', detached: true })
      .on('error', () => spawn('xdg-open', [url], { stdio: 'ignore', detached: true }).unref())
      .unref();
  }
}

function promptEnter(message) {
  return new Promise((resolve) => {
    const rl = createInterface({ input: process.stdin, output: process.stderr });
    rl.question(message, () => { rl.close(); resolve(); });
  });
}

class HttpError extends Error {
  constructor(status, statusText, body) {
    super(`HTTP ${status} ${statusText}: ${typeof body === 'string' ? body.slice(0, 500) : JSON.stringify(body).slice(0, 500)}`);
    this.status = status;
    this.statusText = statusText;
    this.body = body;
  }
}

function sleep(ms) {
  return new Promise((r) => setTimeout(r, ms));
}

// Known OpenAI fields on assistant messages and tool_calls — used to detect
// vendor-specific extras (e.g. Gemini's thought_signature).
const OPENAI_MESSAGE_FIELDS = new Set(['role', 'content', 'tool_calls', 'tool_call_id', 'refusal', 'name', 'function_call']);
const OPENAI_TOOL_CALL_FIELDS = new Set(['id', 'type', 'function', 'index']);
const OPENAI_FUNCTION_FIELDS = new Set(['name', 'arguments']);

function findExtras(obj, knownSet) {
  if (!obj || typeof obj !== 'object') return null;
  const extras = {};
  let any = false;
  for (const k of Object.keys(obj)) {
    if (!knownSet.has(k)) { extras[k] = obj[k]; any = true; }
  }
  return any ? extras : null;
}

function summarizeResponseExtras(json) {
  const out = { messageExtras: null, toolCalls: [] };
  const msg = json?.choices?.[0]?.message;
  if (!msg) return out;
  out.messageExtras = findExtras(msg, OPENAI_MESSAGE_FIELDS);
  for (const tc of msg.tool_calls ?? []) {
    out.toolCalls.push({
      id: tc.id,
      name: tc.function?.name,
      tcExtras: findExtras(tc, OPENAI_TOOL_CALL_FIELDS),
      fnExtras: findExtras(tc.function, OPENAI_FUNCTION_FIELDS),
    });
  }
  return out;
}

function summarizeRequestToolFlow(body) {
  // Pulls out the tool-related shape of what we're SENDING — to verify IDs
  // round-trip.
  const out = { toolDefs: [], assistantToolCallIds: [], toolMessageIds: [] };
  if (Array.isArray(body.tools)) {
    for (const t of body.tools) if (t.function?.name) out.toolDefs.push(t.function.name);
  }
  for (const m of body.messages ?? []) {
    if (m.role === 'assistant' && Array.isArray(m.tool_calls)) {
      for (const tc of m.tool_calls) out.assistantToolCallIds.push(tc.id);
    }
    if (m.role === 'tool' && m.tool_call_id) out.toolMessageIds.push(m.tool_call_id);
  }
  return out;
}

function parseRetryAfter(headers, body) {
  const headerVal = headers.get?.('retry-after');
  const headerSec = headerVal ? Number(headerVal) : NaN;
  const bodySec = Number(body?.retry_after_seconds);
  const candidates = [headerSec, bodySec].filter((n) => Number.isFinite(n) && n > 0);
  if (candidates.length === 0) return 1;
  return Math.max(...candidates);
}

async function readJson(res) {
  const text = await res.text();
  try {
    return JSON.parse(text);
  } catch {
    return { raw: text };
  }
}

/**
 * @param {object} opts
 * @param {string} [opts.baseURL]     Defaults to https://api.genai.mil/v1
 * @param {string} [opts.apiKey]      Bearer token. Defaults to process.env.AGENT_API_KEY.
 * @param {Function} [opts.fetchImpl] Override for tests (default: globalThis.fetch).
 * @param {number}   [opts.maxRetries] Default 3.
 * @param {Function} [opts.onUnlock]   Callback(url) when an unlock is performed (telemetry).
 * @param {Function} [opts.onRateLimit] Callback(ms) when a 429 sleep happens (telemetry).
 * @param {Function} [opts.onUsage]    Callback(usage) on successful response.
 */
function createHttpAdapter(opts = {}) {
  const baseURL = (opts.baseURL ?? process.env.AGENT_BASE_URL ?? DEFAULT_BASE_URL).replace(/\/+$/, '');
  const apiKey = opts.apiKey ?? process.env.AGENT_API_KEY ?? '';
  const fetchImpl = opts.fetchImpl ?? globalThis.fetch;
  const maxRetries = opts.maxRetries ?? 3;
  const onUnlock = opts.onUnlock ?? (() => {});
  const onRateLimit = opts.onRateLimit ?? (() => {});
  const onUsage = opts.onUsage ?? (() => {});
  const debug = opts.debug ?? (process.env.AGENT_DEBUG === '1');
  const onTransaction = opts.onTransaction ?? (() => {});

  if (!fetchImpl) throw new Error('createHttpAdapter: no fetch implementation available');

  async function doFetchOnce(path, init) {
    const url = `${baseURL}${path}`;
    const headers = {
      'content-type': 'application/json',
      accept: init?.body && JSON.parse(init.body).stream ? 'text/event-stream' : 'application/json',
      ...(apiKey ? { authorization: `Bearer ${apiKey}` } : {}),
      ...(init?.headers ?? {}),
    };
    return fetchImpl(url, { ...init, headers });
  }

  async function safeFetch(path, init) {
    let attempt = 0;
    let unlocked = false;
    while (true) {
      const res = await doFetchOnce(path, init);
      if (res.ok) return res;

      if (res.status === 401 && !unlocked) {
        const body = await readJson(res);
        const unlockUrl = body?.unlock_url ?? body?.error?.unlock_url;
        if (unlockUrl) {
          onUnlock(unlockUrl);
          if (opts.openBrowser !== false) openInBrowser(unlockUrl);
          await promptEnter(`\n[unlock] API key is locked. A browser tab should have opened:\n  ${unlockUrl}\nUnlock the key in your browser, then press Enter to retry... `);
          unlocked = true;
          continue;
        }
        throw new HttpError(res.status, res.statusText, body);
      }

      if (res.status === 429 && attempt < maxRetries) {
        const body = await readJson(res);
        const waitSec = parseRetryAfter(res.headers, body);
        const waitMs = Math.max(waitSec * 1000, 500 * Math.pow(2, attempt));
        onRateLimit(waitMs);
        await sleep(waitMs);
        attempt++;
        continue;
      }

      const body = await readJson(res);
      throw new HttpError(res.status, res.statusText, body);
    }
  }

  async function complete(request) {
    if (!request || !Array.isArray(request.messages)) {
      throw new TypeError('complete: request.messages is required');
    }
    const body = { ...request, stream: false };
    if (debug) {
      const flow = summarizeRequestToolFlow(body);
      console.error(`[http>] complete  tools=[${flow.toolDefs.join(',')}]`);
      if (flow.assistantToolCallIds.length) console.error(`[http>]   assistant.tool_calls ids: ${JSON.stringify(flow.assistantToolCallIds)}`);
      if (flow.toolMessageIds.length) console.error(`[http>]   tool message ids:           ${JSON.stringify(flow.toolMessageIds)}`);
    }
    const t0 = Date.now();
    // Snapshot the request shape BEFORE we send, because the agent loop
    // shares its messages array by reference and will mutate it after the
    // call returns. Without this clone, snapshots show a misleading body.
    const requestSnapshot = JSON.parse(JSON.stringify(body));
    const res = await safeFetch('/chat/completions', { method: 'POST', body: JSON.stringify(body) });
    const json = await res.json();
    onTransaction({ type: 'chat_completions', request: requestSnapshot, response: json, durationMs: Date.now() - t0 });
    if (debug) {
      const summary = summarizeResponseExtras(json);
      const finish = json?.choices?.[0]?.finish_reason;
      console.error(`[http<] complete  finish=${finish}`);
      if (summary.messageExtras) console.error(`[http<]   message extras: ${JSON.stringify(summary.messageExtras).slice(0, 400)}`);
      for (const tc of summary.toolCalls) {
        console.error(`[http<]   tool_call id=${tc.id} name=${tc.name}` + (tc.tcExtras ? ` extras=${JSON.stringify(tc.tcExtras)}` : '') + (tc.fnExtras ? ` fn_extras=${JSON.stringify(tc.fnExtras)}` : ''));
      }
    }
    if (json.usage) onUsage(json.usage);
    return json;
  }

  async function* completeStream(request) {
    if (!request || !Array.isArray(request.messages)) {
      throw new TypeError('completeStream: request.messages is required');
    }
    const body = { ...request, stream: true };
    if (debug) {
      const flow = summarizeRequestToolFlow(body);
      console.error(`[http>] completeStream  tools=[${flow.toolDefs.join(',')}]`);
      if (flow.assistantToolCallIds.length) console.error(`[http>]   assistant.tool_calls ids: ${JSON.stringify(flow.assistantToolCallIds)}`);
      if (flow.toolMessageIds.length) console.error(`[http>]   tool message ids:           ${JSON.stringify(flow.toolMessageIds)}`);
    }
    const res = await safeFetch('/chat/completions', { method: 'POST', body: JSON.stringify(body) });

    if (!res.body) throw new Error('completeStream: response has no body');

    const reader = res.body.getReader();
    const decoder = new TextDecoder();
    let buf = '';
    let usageFired = false;
    const fireUsageOnce = (u) => {
      if (u && !usageFired) {
        usageFired = true;
        onUsage(u);
      }
    };

    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      buf += decoder.decode(value, { stream: true });

      let idx;
      while ((idx = buf.indexOf('\n')) !== -1) {
        const line = buf.slice(0, idx).replace(/\r$/, '');
        buf = buf.slice(idx + 1);
        if (!line || line.startsWith(':')) continue;
        if (!line.startsWith('data:')) continue;
        const data = line.slice(5).trim();
        if (data === '[DONE]') return;
        try {
          const chunk = JSON.parse(data);
          fireUsageOnce(chunk.usage);
          yield chunk;
        } catch {
          // ignore malformed line
        }
      }
    }
  }

  async function listModels() {
    const t0 = Date.now();
    const res = await safeFetch('/models', { method: 'GET' });
    const json = await res.json();
    onTransaction({ type: 'list_models', request: null, response: json, durationMs: Date.now() - t0 });
    return json;
  }

  return { complete, completeStream, listModels };
}

// ====== agent/tools.mjs ======
/**
 * Initial agent tools — read-only. Pure Node, no deps.
 *
 * Each tool: { schema, impl }
 *   schema   — OpenAI function tool descriptor (description + JSON Schema)
 *   impl     — async ({ args }) => string (stringified result; errors caught
 *              and returned as 'ERROR: ...' so the loop can decide what to do)
 *
 * Result strings are capped at MAX_RESULT_BYTES to keep tool feedback from
 * blowing up the context window. Truncation is explicitly marked.
 */

const IGNORE_DIRS = new Set(['node_modules', '.git', 'dist', '.agent', 'coverage']);
const TEXT_EXTS = new Set([
  '.mjs', '.js', '.ts', '.tsx', '.jsx', '.json', '.md', '.txt', '.yml', '.yaml',
  '.sh', '.ps1', '.bat', '.cmd', '.py', '.go', '.rs', '.java', '.xml', '.html',
  '.css', '.scss', '.sql', '.toml', '.ini', '.env', '.gitignore', '',
]);

// Hard ceiling per tool result. Million-token context affords generous limits;
// this only exists to refuse pathological cases (multi-MB binary-like blobs).
// When a result would exceed this, return an ERROR instead of silently
// truncating — the model can retry with offset/limit.
const MAX_RESULT_BYTES = 2 * 1024 * 1024; // 2 MB
const MAX_GREP_MATCHES = 2000;
const MAX_GLOB_RESULTS = 5000;

class TooLargeError extends Error {
  constructor(actualBytes) {
    super(`result would be ${actualBytes} bytes, exceeds ${MAX_RESULT_BYTES}-byte ceiling`);
    this.actualBytes = actualBytes;
  }
}

function ensureFits(s) {
  if (s.length > MAX_RESULT_BYTES) throw new TooLargeError(s.length);
  return s;
}

function isTextFile(p) {
  const ext = path.extname(p).toLowerCase();
  if (TEXT_EXTS.has(ext)) return true;
  return false;
}

function globToRegex(glob) {
  // Convert a glob to a regex. Supports: ** (any path), * (any non-separator), ? (one char), {a,b}.
  let re = '';
  for (let i = 0; i < glob.length; i++) {
    const c = glob[i];
    if (c === '*') {
      if (glob[i + 1] === '*') {
        // ** — any chars including /
        re += '.*';
        i++;
        if (glob[i + 1] === '/') i++;
      } else {
        re += '[^/\\\\]*';
      }
    } else if (c === '?') {
      re += '[^/\\\\]';
    } else if (c === '.') {
      re += '\\.';
    } else if (c === '{') {
      const end = glob.indexOf('}', i);
      if (end === -1) { re += '\\{'; continue; }
      const parts = glob.slice(i + 1, end).split(',').map((s) => s.replace(/\./g, '\\.'));
      re += `(?:${parts.join('|')})`;
      i = end;
    } else if ('+()|^$/\\'.includes(c)) {
      re += '\\' + c;
    } else {
      re += c;
    }
  }
  return new RegExp('^' + re + '$');
}

async function walkDir(root, { maxDepth = 12 } = {}) {
  const out = [];
  async function rec(dir, depth) {
    if (depth > maxDepth) return;
    let entries;
    try { entries = await readdir(dir, { withFileTypes: true }); }
    catch { return; }
    for (const e of entries) {
      if (e.isDirectory()) {
        if (IGNORE_DIRS.has(e.name)) continue;
        await rec(path.join(dir, e.name), depth + 1);
      } else if (e.isFile()) {
        out.push(path.join(dir, e.name));
      }
    }
  }
  await rec(root, 0);
  return out;
}

function relForDisplay(p) {
  return path.relative(process.cwd(), p).split(path.sep).join('/');
}

async function safeReadText(p) {
  const s = await stat(p);
  if (s.size > MAX_RESULT_BYTES) throw new TooLargeError(s.size);
  const buf = await readFile(p);
  // Reject obvious binaries: NUL byte in first 8KB.
  const sample = buf.subarray(0, Math.min(8192, buf.length));
  for (let i = 0; i < sample.length; i++) {
    if (sample[i] === 0) throw new Error('binary file');
  }
  return buf.toString('utf8');
}

const tools = {
  file_info: {
    schema: {
      description: 'Get metadata for a file without reading its contents. Returns byte size and line count. Cheap — use this to plan reads of large files before calling read_file.',
      parameters: {
        type: 'object',
        properties: {
          path: { type: 'string', description: 'Absolute or project-relative file path.' },
        },
        required: ['path'],
        additionalProperties: false,
      },
    },
    impl: async ({ path: p }) => {
      if (typeof p !== 'string' || !p) throw new Error('path is required');
      const abs = path.isAbsolute(p) ? p : path.join(process.cwd(), p);
      const s = await stat(abs);
      let lines = null;
      if (s.size <= MAX_RESULT_BYTES) {
        const buf = await readFile(abs);
        const sample = buf.subarray(0, Math.min(8192, buf.length));
        let isBinary = false;
        for (let i = 0; i < sample.length; i++) if (sample[i] === 0) { isBinary = true; break; }
        lines = isBinary ? null : buf.toString('utf8').split('\n').length;
      }
      return JSON.stringify({ path: relForDisplay(abs), bytes: s.size, lines });
    },
  },

  read_file: {
    schema: {
      description: `Read a UTF-8 text file. If the slice would exceed ${MAX_RESULT_BYTES} bytes, the call ERRORs — retry with offset/limit to chunk the read. Use file_info first if you're unsure of file size.`,
      parameters: {
        type: 'object',
        properties: {
          path: { type: 'string', description: 'Absolute or project-relative file path.' },
          offset: { type: 'integer', description: 'Optional 1-indexed starting LINE number (NOT bytes). Defaults to line 1.' },
          limit: { type: 'integer', description: 'Optional max number of LINES to read (NOT bytes). If omitted, reads to end of file.' },
        },
        required: ['path'],
        additionalProperties: false,
      },
    },
    impl: async ({ path: p, offset, limit }) => {
      if (typeof p !== 'string' || !p) throw new Error('path is required');
      const abs = path.isAbsolute(p) ? p : path.join(process.cwd(), p);
      const text = await safeReadText(abs);
      if (offset == null && limit == null) return ensureFits(text);
      const lines = text.split('\n');
      const start = Math.max(0, (offset ?? 1) - 1);
      const end = limit != null ? start + limit : lines.length;
      const slice = lines.slice(start, end).join('\n');
      return ensureFits(slice);
    },
  },

  grep: {
    schema: {
      description: 'Search files in the project for a regular expression. Returns matching lines with file:line prefix. Up to ' + MAX_GREP_MATCHES + ' matches.',
      parameters: {
        type: 'object',
        properties: {
          pattern: { type: 'string', description: 'JavaScript regex pattern (no slashes).' },
          path: { type: 'string', description: 'Optional subdirectory to search. Defaults to project root.' },
          glob: { type: 'string', description: 'Optional glob filter for file paths (e.g. "**/*.mjs").' },
          flags: { type: 'string', description: 'Optional regex flags (e.g. "i" for case-insensitive).' },
        },
        required: ['pattern'],
        additionalProperties: false,
      },
    },
    impl: async ({ pattern, path: subPath, glob, flags }) => {
      if (typeof pattern !== 'string' || !pattern) throw new Error('pattern is required');
      const re = new RegExp(pattern, flags ?? '');
      const root = subPath
        ? (path.isAbsolute(subPath) ? subPath : path.join(process.cwd(), subPath))
        : process.cwd();
      const globRe = glob ? globToRegex(glob) : null;
      const files = await walkDir(root);
      const lines = [];
      let count = 0;
      outer: for (const f of files) {
        if (globRe && !globRe.test(relForDisplay(f).replace(/\\/g, '/'))) continue;
        if (!isTextFile(f)) continue;
        let text;
        try { text = await safeReadText(f); } catch { continue; }
        const ls = text.split('\n');
        for (let i = 0; i < ls.length; i++) {
          if (re.test(ls[i])) {
            lines.push(`${relForDisplay(f)}:${i + 1}:${ls[i]}`);
            count++;
            if (count >= MAX_GREP_MATCHES) {
              lines.push(`\n[stopped at ${MAX_GREP_MATCHES} matches]`);
              break outer;
            }
          }
        }
      }
      return ensureFits(lines.length ? lines.join('\n') : '(no matches)');
    },
  },

  glob: {
    schema: {
      description: 'Find files in the project matching a glob pattern (e.g. "src/**/*.mjs"). Returns up to ' + MAX_GLOB_RESULTS + ' paths.',
      parameters: {
        type: 'object',
        properties: {
          pattern: { type: 'string', description: 'Glob pattern. Supports **, *, ?, {a,b}.' },
        },
        required: ['pattern'],
        additionalProperties: false,
      },
    },
    impl: async ({ pattern }) => {
      if (typeof pattern !== 'string' || !pattern) throw new Error('pattern is required');
      const re = globToRegex(pattern);
      const files = await walkDir(process.cwd());
      const out = [];
      for (const f of files) {
        const rel = relForDisplay(f).replace(/\\/g, '/');
        if (re.test(rel)) {
          out.push(rel);
          if (out.length >= MAX_GLOB_RESULTS) {
            out.push(`[stopped at ${MAX_GLOB_RESULTS} results]`);
            break;
          }
        }
      }
      return ensureFits(out.length ? out.join('\n') : '(no matches)');
    },
  },

  list_dir: {
    schema: {
      description: 'List entries in a directory. Returns each entry as "[D] name/" or "[F] name (<bytes> bytes)".',
      parameters: {
        type: 'object',
        properties: {
          path: { type: 'string', description: 'Absolute or project-relative directory path. Defaults to project root.' },
        },
        required: [],
        additionalProperties: false,
      },
    },
    impl: async ({ path: p }) => {
      const dir = p
        ? (path.isAbsolute(p) ? p : path.join(process.cwd(), p))
        : process.cwd();
      const entries = await readdir(dir, { withFileTypes: true });
      const lines = [];
      for (const e of entries.sort((a, b) => a.name.localeCompare(b.name))) {
        if (e.isDirectory()) {
          lines.push(`[D] ${e.name}/`);
        } else {
          let size = '';
          try {
            const s = await stat(path.join(dir, e.name));
            size = `(${s.size} bytes)`;
          } catch {}
          lines.push(`[F] ${e.name} ${size}`.trim());
        }
      }
      return ensureFits(lines.join('\n'));
    },
  },
};

const toolDefs = Object.entries(tools).map(([name, t]) => ({
  type: 'function',
  function: { name, description: t.schema.description, parameters: t.schema.parameters },
}));

async function execute(name, args) {
  const t = tools[name];
  if (!t) return `ERROR: unknown tool "${name}". Available: ${Object.keys(tools).join(', ')}`;
  try {
    const result = await t.impl(args ?? {});
    return typeof result === 'string' ? result : JSON.stringify(result);
  } catch (e) {
    return `ERROR: ${e.message}`;
  }
}

// ====== agent/prompted.mjs ======
/**
 * Prompted-format file access — the "local workspace bridge".
 *
 * The production endpoint (api.genai.mil) is a managed-agent platform that
 * drops the OpenAI `tools` parameter AND injects its own cloud tools/agents
 * (e.g. "Generate Document", a cloud Python sandbox). Telling the model "you
 * have no tools, use only ours" made it conflict with those built-ins and
 * freeze. So we DON'T frame our mechanism as "tools" at all.
 *
 * Instead we present a distinct concept: a LOCAL WORKSPACE BRIDGE — a text
 * channel to the user's real machine. The model's built-in tools run in a
 * cloud environment and genuinely cannot see the user's local project, so the
 * bridge is simply the way to reach those files. Positive framing only; no
 * "NOT this / NEVER that" instructions that cause paralysis.
 *
 * Wire format (model -> us): a <workspace> block of verb elements with
 * attributes (a separate visual concept from `<call name="tool">`):
 *
 *   <workspace>
 *     <list path="."/>
 *     <read path="pom.xml" limit="100"/>
 *     <search pattern="dependency" flags="i"/>
 *   </workspace>
 *
 * Feedback (us -> model), a normal user message:
 *   <workspace-result op="read" status="ok">
 *   ...real contents...
 *   </workspace-result>
 */

// Friendly workspace verbs -> internal tool names.
const VERB_TO_TOOL = {
  list: 'list_dir',
  read: 'read_file',
  search: 'grep',
  find: 'glob',
  info: 'file_info',
};
const VERBS = Object.keys(VERB_TO_TOOL).join('|');
const OP_RE = new RegExp(`<(${VERBS})\\b([^>]*)>`, 'gi');
const ATTR_RE = /([a-zA-Z_]+)\s*=\s*"([^"]*)"/g;

const DEFAULT_MAX_TURNS = 15;
const REPEAT_LIMIT = 3;

function buildSystemPrompt() {
  return [
    'You are a coding assistant connected to a REMOTE WORKSPACE — the user\'s own computer, where the project you are helping with actually lives. The remote workspace is separate from your native workspace (your built-in cloud environment); the project exists only in the remote workspace.',
    '',
    'Your job is to operate in the remote workspace by issuing commands to it. Each command runs on the user\'s real filesystem and returns the actual results.',
    '',
    'To issue commands, emit a <remote-workspace> block containing one or more commands, then stop and wait for the results:',
    '',
    '<remote-workspace>',
    '  <list path="."/>',
    '  <read path="pom.xml"/>',
    '  <search pattern="dependency"/>',
    '</remote-workspace>',
    '',
    'The remote workspace replies with <remote-workspace-result> blocks containing the real contents from the user\'s machine. Read those, then issue more commands or answer the user. Group independent commands in one block — they run in parallel, which is faster.',
    '',
    'Commands available in the remote workspace:',
    '  <list path="DIR"/>                                  list a directory (path optional; defaults to project root)',
    '  <read path="FILE" offset="LINE" limit="N"/>          read a UTF-8 text file (offset/limit optional)',
    '  <search pattern="REGEX" path="DIR" glob="GLOB" flags="i"/>   regex search across files (only pattern required)',
    '  <find pattern="GLOB"/>                               find files by glob, e.g. src/**/*.mjs',
    '  <info path="FILE"/>                                  file size and line count (cheap; use before reading big files)',
    '',
    'Base every answer on results returned from the remote workspace. If you have not read a file through the remote workspace, issue a command to read it rather than guessing its contents.',
  ].join('\n');
}

function coerce(toolName, key, raw) {
  const ptype = tools[toolName]?.schema?.parameters?.properties?.[key]?.type;
  const val = String(raw).trim();
  if (ptype === 'integer' || ptype === 'number') {
    const n = Number(val);
    return Number.isNaN(n) ? val : n;
  }
  if (ptype === 'boolean') return val === 'true';
  return val;
}

function mkId() {
  return 'call_' + randomUUID().replace(/-/g, '').slice(0, 16);
}

function parseToolCalls(text) {
  const calls = [];
  if (typeof text !== 'string' || !text) return calls;
  OP_RE.lastIndex = 0;
  let m;
  while ((m = OP_RE.exec(text)) !== null) {
    const verb = m[1].toLowerCase();
    const toolName = VERB_TO_TOOL[verb];
    if (!toolName) continue;
    const attrStr = m[2] ?? '';
    const args = {};
    ATTR_RE.lastIndex = 0;
    let a;
    while ((a = ATTR_RE.exec(attrStr)) !== null) {
      args[a[1]] = coerce(toolName, a[1], a[2]);
    }
    calls.push({ id: mkId(), verb, name: toolName, args });
  }
  return calls;
}

function formatToolResults(results) {
  const blocks = results.map((r) =>
    `<remote-workspace-result op="${r.verb}" status="${r.status}">\n${r.content}\n</remote-workspace-result>`,
  ).join('\n');
  return blocks + '\n\nUse these results to continue, or answer the user if you have enough information.';
}

/** Strip the <remote-workspace> block out of assistant text so we show only prose. */
function proseBefore(text) {
  if (typeof text !== 'string') return '';
  const idx = text.search(/<remote-workspace>/i);
  return (idx === -1 ? text : text.slice(0, idx)).trim();
}

function flattenContent(content) {
  if (content == null) return '';
  if (typeof content === 'string') return content;
  if (Array.isArray(content)) {
    return content.map((p) => (typeof p === 'string' ? p : p?.type === 'text' ? p.text ?? '' : '')).join('');
  }
  return String(content);
}

/**
 * The production endpoint frequently ignores or overrides the `system`
 * message with its own platform prompt — the model reports it knows nothing
 * about the remote workspace. So we inject the instructions into the FIRST
 * user message (wrapped in <system-reminder>), which the platform cannot
 * strip because it's the actual query. No separate system message is sent.
 */
function injectInstructions(messages) {
  const instructions = buildSystemPrompt();
  const nonSystem = (messages ?? []).filter((m) => m.role !== 'system');
  const out = [];
  let injected = false;
  for (const m of nonSystem) {
    if (!injected && m.role === 'user') {
      out.push({ role: 'user', content: `<system-reminder>\n${instructions}\n</system-reminder>\n\n${flattenContent(m.content)}` });
      injected = true;
    } else {
      out.push(m);
    }
  }
  if (!injected) {
    out.unshift({ role: 'user', content: `<system-reminder>\n${instructions}\n</system-reminder>` });
  }
  return out;
}

async function runPromptedAgent({ adapter, messages, model, maxTurns = DEFAULT_MAX_TURNS, onTurn }) {
  const convo = injectInstructions(messages);

  const stats = { turns: 0, toolCalls: 0, toolHistogram: {}, batches: [], loopBreaks: 0 };
  let lastKey = '';
  let repeat = 0;

  for (let turn = 1; turn <= maxTurns; turn++) {
    stats.turns = turn;
    const res = await adapter.complete({ model, messages: convo, stop: ['</remote-workspace>'] });
    const text = res.choices?.[0]?.message?.content ?? '';
    const calls = parseToolCalls(text);

    if (onTurn) onTurn({ turn, text, calls, stats });

    if (calls.length === 0) {
      return { content: text, stats, terminated: 'stop', convo };
    }
    stats.batches.push(calls.length);

    const assistantText = /<\/remote-workspace>/i.test(text) ? text : `${text}\n</remote-workspace>`;
    convo.push({ role: 'assistant', content: assistantText });

    const results = [];
    for (const c of calls) {
      stats.toolCalls++;
      stats.toolHistogram[c.name] = (stats.toolHistogram[c.name] ?? 0) + 1;
      const key = c.name + '|' + JSON.stringify(c.args);
      if (key === lastKey) repeat++; else { lastKey = key; repeat = 1; }
      let content;
      if (repeat >= REPEAT_LIMIT) {
        stats.loopBreaks++;
        content = `LOOP DETECTED: this exact request has fired ${repeat} times. Stop requesting and answer with what you have.`;
      } else {
        content = await execute(c.name, c.args);
      }
      results.push({ verb: c.verb, status: content.startsWith('ERROR') ? 'error' : 'ok', content });
    }
    convo.push({ role: 'user', content: formatToolResults(results) });
  }

  return { content: '[MAX TURNS REACHED — agent did not converge]', stats, terminated: 'max-turns', convo };
}

// ====== server.mjs ======
/**
 * Local HTTP server for the code_boss web UI. Binds to 127.0.0.1 only.
 *
 * Routes:
 *   GET  /                   serve the HTML page
 *   GET  /api/models         proxy to BASE_URL/models
 *   POST /api/chat           proxy chat completions, streams SSE back to browser
 *   GET  /api/snapshot       session state for the in-page snapshot modal
 *   POST /api/reset          clear the session log
 *   GET  /api/health         ping
 *
 * The server tracks every adapter transaction in `session.events`. The
 * snapshot endpoint returns these for client-side rendering.
 *
 * No npm deps. Node built-in http + the production HTTP adapter.
 */

const RECENT_FILE = path.join(homedir(), '.code-boss', 'recent.json');
const MAX_RECENT = 12;

async function loadRecentProjects() {
  try {
    const text = await readFile(RECENT_FILE, 'utf8');
    const data = JSON.parse(text);
    return Array.isArray(data?.projects) ? data.projects.filter((p) => typeof p === 'string') : [];
  } catch { return []; }
}
async function saveRecentProjects(projects) {
  try {
    await mkdir(path.dirname(RECENT_FILE), { recursive: true });
    await writeFile(RECENT_FILE, JSON.stringify({ projects }, null, 2), 'utf8');
  } catch (e) { console.error('[recent] save failed:', e.message); }
}

/** Open a native folder-picker dialog; resolve to the selected absolute path
 *  or null if the user canceled. */
function pickFolderNative() {
  return new Promise((resolve) => {
    let cmd, args, parseStdout = (s) => s.trim() || null;
    if (process.platform === 'win32') {
      cmd = 'powershell';
      args = ['-NoProfile', '-STA', '-Command',
        "Add-Type -AssemblyName System.Windows.Forms | Out-Null; " +
        "$f = New-Object System.Windows.Forms.FolderBrowserDialog; " +
        "$f.Description = 'Choose a project folder'; " +
        "if ($f.ShowDialog() -eq [System.Windows.Forms.DialogResult]::OK) { Write-Output $f.SelectedPath }"];
    } else if (process.platform === 'darwin') {
      cmd = 'osascript';
      args = ['-e', 'POSIX path of (choose folder with prompt "Choose a project folder")'];
    } else {
      cmd = 'zenity';
      args = ['--file-selection', '--directory', '--title=Choose a project folder'];
    }
    // Do NOT pass windowsHide:true — that suppresses the dialog window too.
    const ps = spawn(cmd, args, { stdio: ['ignore', 'pipe', 'pipe'] });
    let out = '';
    ps.stdout.on('data', (d) => (out += d.toString()));
    ps.on('error', () => resolve(null));
    ps.on('close', () => resolve(parseStdout(out)));
  });
}

const SUMMARIZE = {
  list_models: (d) => `list_models  →  ${d.response?.data?.length ?? '?'} models  (${d.durationMs}ms)`,
  chat_completions: (d) => {
    const fr = d.response?.choices?.[0]?.finish_reason ?? '?';
    const u = d.response?.usage ?? {};
    return `chat_completions  →  finish=${fr}  tokens=${u.total_tokens ?? '?'}  (${d.durationMs}ms)`;
  },
  unlock: (d) => `unlock  →  ${d.url}`,
  'rate-limit': (d) => `rate-limit  →  sleep ${d.ms}ms`,
  usage: (d) => `usage  →  ${JSON.stringify(d)}`,
  error: (d) => `error: ${d.message}`,
};

async function startServer({ html, baseURL, apiKey, defaultModel, port = 18888, adapter: providedAdapter, modelsList, initialProject = null }) {
  const session = {
    startedAt: new Date().toISOString(),
    baseURL: baseURL ?? '(dev)',
    defaultModel,
    apiKeyPrefix: (apiKey || '').slice(0, 8) + (apiKey ? '…' : '(empty)'),
    events: [],
    totalTokens: 0,
    startMs: Date.now(),
    activeProject: null,
    recent: await loadRecentProjects(),
  };

  async function openProject(p) {
    if (typeof p !== 'string' || !p) throw new Error('invalid project path');
    try {
      const s = await stat(p);
      if (!s.isDirectory()) throw new Error('not a directory');
    } catch (e) { throw new Error('cannot open: ' + e.message); }
    session.activeProject = p;
    session.recent = [p, ...session.recent.filter((x) => x !== p)].slice(0, MAX_RECENT);
    await saveRecentProjects(session.recent);
    logEvent('project-opened', { path: p });
  }
  function logEvent(type, data) {
    const summary = (SUMMARIZE[type] ?? ((d) => JSON.stringify(d).slice(0, 200)))(data);
    session.events.push({ at: Date.now() - session.startMs, type, summary, ...truncateForSnapshot(data) });
  }
  function truncateForSnapshot(data) {
    // Keep raw request/response for the last transaction view in the modal,
    // but trim huge fields so the snapshot JSON stays manageable.
    if (!data || typeof data !== 'object') return { data };
    const out = { ...data };
    if (out.response && typeof out.response === 'object') {
      const r = out.response;
      const str = JSON.stringify(r);
      if (str.length > 20000) out.response = JSON.parse(str.slice(0, 20000) + '"truncated":true}');
    }
    return out;
  }

  // Use a caller-provided adapter (e.g. the dev claude-code-headless adapter)
  // if given; otherwise default to a fresh production HTTP adapter.
  const adapter = providedAdapter ?? createHttpAdapter({
    baseURL, apiKey,
    onUnlock: (url) => logEvent('unlock', { url }),
    onRateLimit: (ms) => logEvent('rate-limit', { ms }),
    onUsage: (u) => { session.totalTokens += u.total_tokens ?? 0; logEvent('usage', u); },
    onTransaction: (t) => logEvent(t.type, t),
  });

  async function readBody(req) {
    const chunks = [];
    for await (const c of req) chunks.push(c);
    return Buffer.concat(chunks).toString('utf8');
  }
  function sendJson(res, status, body) {
    const s = JSON.stringify(body);
    res.writeHead(status, { 'content-type': 'application/json', 'content-length': Buffer.byteLength(s) });
    res.end(s);
  }
  function sendText(res, status, text, type = 'text/plain') {
    res.writeHead(status, { 'content-type': type, 'content-length': Buffer.byteLength(text) });
    res.end(text);
  }

  const server = createServer(async (req, res) => {
    try {
      const url = new URL(req.url, `http://${req.headers.host}`);
      const path = url.pathname;

      if (req.method === 'GET' && path === '/') {
        return sendText(res, 200, html, 'text/html; charset=utf-8');
      }
      if (req.method === 'GET' && path === '/api/health') {
        return sendJson(res, 200, { ok: true });
      }
      if (req.method === 'GET' && path === '/api/state') {
        return sendJson(res, 200, { activeProject: session.activeProject, recent: session.recent });
      }
      if (req.method === 'POST' && path === '/api/pick-folder') {
        const chosen = await pickFolderNative();
        return sendJson(res, 200, { path: chosen });
      }
      if (req.method === 'POST' && path === '/api/open-project') {
        const raw = await readBody(req);
        let body;
        try { body = JSON.parse(raw); }
        catch { return sendJson(res, 400, { error: 'invalid JSON' }); }
        try { await openProject(body.path); }
        catch (e) { return sendJson(res, 400, { error: e.message }); }
        return sendJson(res, 200, { activeProject: session.activeProject, recent: session.recent });
      }
      if (req.method === 'POST' && path === '/api/close-project') {
        session.activeProject = null;
        return sendJson(res, 200, { activeProject: null, recent: session.recent });
      }
      if (req.method === 'GET' && path === '/api/models') {
        // Dev mode passes a static modelsList; prod uses the adapter.
        if (modelsList) return sendJson(res, 200, { data: modelsList });
        const data = await adapter.listModels();
        return sendJson(res, 200, data);
      }
      if (req.method === 'GET' && path === '/api/snapshot') {
        // Aggregate parallel-tool-batch stats from every agent_run event.
        const agentRuns = session.events.filter((e) => e.type === 'agent_run');
        const allBatches = agentRuns.flatMap((e) => Array.isArray(e.batches) ? e.batches : []);
        const sum = allBatches.reduce((s, n) => s + n, 0);
        const parallelism = {
          runs: agentRuns.length,
          turnsWithTools: allBatches.length,
          totalToolCalls: sum,
          avgPerTurn: allBatches.length ? +(sum / allBatches.length).toFixed(2) : 0,
          maxParallel: allBatches.length ? Math.max(...allBatches) : 0,
          singleCallTurns: allBatches.filter((n) => n === 1).length,
          multiCallTurns: allBatches.filter((n) => n > 1).length,
          batches: allBatches,
        };
        return sendJson(res, 200, {
          startedAt: session.startedAt,
          baseURL: session.baseURL,
          defaultModel: session.defaultModel,
          apiKeyPrefix: session.apiKeyPrefix,
          activeProject: session.activeProject,
          totalTokens: session.totalTokens,
          parallelism,
          events: session.events,
        });
      }
      if (req.method === 'POST' && path === '/api/reset') {
        session.events = [];
        session.totalTokens = 0;
        session.startMs = Date.now();
        return sendJson(res, 200, { ok: true });
      }
      if (req.method === 'POST' && path === '/api/chat') {
        const raw = await readBody(req);
        const body = JSON.parse(raw);
        res.writeHead(200, {
          'content-type': 'text/event-stream',
          'cache-control': 'no-cache',
          'connection': 'keep-alive',
        });

        const send = (chunk) => res.write(`data: ${JSON.stringify(chunk)}\n\n`);
        const emitText = (text) => send({
          id: 'agent', object: 'chat.completion.chunk',
          choices: [{ index: 0, delta: { content: text }, finish_reason: null }],
        });
        const emitFinish = (reason, usage) => send({
          id: 'agent', object: 'chat.completion.chunk',
          choices: [{ index: 0, delta: {}, finish_reason: reason }],
          ...(usage ? { usage } : {}),
        });

        // Point the agent's read tools at the active project. Single-user
        // local app — process.chdir for the duration of the request is OK.
        const prevCwd = process.cwd();
        let cwdChanged = false;
        if (session.activeProject) {
          try { process.chdir(session.activeProject); cwdChanged = true; }
          catch (e) {
            emitText(`(error: cannot enter project directory: ${e.message})`);
            emitFinish('stop');
            res.write('data: [DONE]\n\n');
            return res.end();
          }
        } else {
          emitText('(no project open — pick one from the picker first)\n');
          emitFinish('stop');
          res.write('data: [DONE]\n\n');
          return res.end();
        }

        try {
          let lastTurnHadContent = false;
          let lastTurnHadTools = false;
          const result = await runPromptedAgent({
            adapter,
            messages: body.messages,
            model: body.model,
            maxTurns: 15,
            onTurn: ({ turn, text, calls }) => {
              lastTurnHadTools = calls.length > 0;
              lastTurnHadContent = !!(text && text.trim().length > 0);
              if (calls.length > 0) {
                const prose = proseBefore(text);
                if (prose) emitText(prose + '\n');
                for (const c of calls) {
                  emitText(`\n🔧 \`${c.name}(${JSON.stringify(c.args)})\`\n`);
                }
              } else if (text) {
                emitText(text);
              }
            },
          });
          // Detect the "model returned nothing useful" case.
          if (!lastTurnHadContent && !lastTurnHadTools && (!result.content || result.content.trim().length === 0)) {
            emitText('\n⚠️ Model returned an empty response (terminated=' +
              (result.terminated ?? 'unknown') +
              '). Open the Snapshot to see the raw response.\n');
          }
          emitFinish('stop', { total_tokens: result.stats.toolCalls });
          logEvent('agent_run', {
            turns: result.stats.turns,
            toolCalls: result.stats.toolCalls,
            batches: result.stats.batches,
            terminated: result.terminated,
          });
        } catch (e) {
          logEvent('error', { message: e.message });
          send({ error: { message: e.message, stack: e.stack } });
        } finally {
          if (cwdChanged) process.chdir(prevCwd);
          res.write('data: [DONE]\n\n');
          res.end();
        }
        return;
      }
      sendText(res, 404, 'Not found');
    } catch (e) {
      logEvent('error', { message: e.message });
      const body = JSON.stringify({ error: { message: e.message, stack: e.stack } });
      res.writeHead(500, { 'content-type': 'application/json' });
      res.end(body);
    }
  });

  if (initialProject) {
    try { await openProject(initialProject); }
    catch (e) { console.error('[server] could not open initial project:', e.message); }
  }

  return new Promise((resolve, reject) => {
    server.once('error', reject);
    server.listen(port, '127.0.0.1', () => resolve({ server, session, port }));
  });
}

// ====== cli-picker.mjs ======
/**
 * Interactive CLI prompt: choose a project to open before the web UI starts.
 *
 * Menu shape:
 *   [1] <current working directory>   (★ initialized | new project)
 *   [2] Open a different folder...    (spawns native dialog)
 *   Recent:
 *   [3..6] up to four recent projects (★ initialized | new project)
 *
 * Returns the absolute path of the chosen folder. Falls back to cwd in a
 * non-TTY environment.
 */

const C = process.stdout.isTTY
  ? { reset:'\x1b[0m', bold:'\x1b[1m', dim:'\x1b[2m', green:'\x1b[32m', cyan:'\x1b[36m', yellow:'\x1b[33m' }
  : new Proxy({}, { get: () => '' });

async function isInitialized(dir) {
  try {
    return (await stat(path.join(dir, '.agent'))).isDirectory();
  } catch { return false; }
}

function prompt(question) {
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  return new Promise((r) => rl.question(question, (a) => { rl.close(); r(a); }));
}

function markerFor(init) {
  return init
    ? `${C.green}★ initialized${C.reset}`
    : `${C.dim}new project${C.reset}`;
}

async function selectProject({ recent = [], cwd = process.cwd() } = {}) {
  // Non-interactive fallback: just use cwd.
  if (!process.stdin.isTTY) {
    console.error(`[cli-picker] non-TTY, defaulting to cwd: ${cwd}`);
    return cwd;
  }

  const cwdInit = await isInitialized(cwd);
  const recentFiltered = recent.filter((p) => p !== cwd).slice(0, 4);
  const recentInfo = await Promise.all(
    recentFiltered.map(async (p) => ({ path: p, init: await isInitialized(p) })),
  );

  console.log('');
  console.log(`  ${C.bold}code_boss${C.reset}`);
  console.log(`  ${C.dim}─────────${C.reset}`);
  console.log('');
  console.log('  Open a project:');
  console.log('');

  const choices = [];
  console.log(`  ${C.cyan}[1]${C.reset} ${cwd}    ${markerFor(cwdInit)}`);
  choices.push({ kind: 'path', value: cwd });

  console.log(`  ${C.cyan}[2]${C.reset} ${C.dim}Open a different folder…${C.reset}`);
  choices.push({ kind: 'pick' });

  if (recentInfo.length > 0) {
    console.log('');
    console.log(`  ${C.dim}Recent:${C.reset}`);
    for (let i = 0; i < recentInfo.length; i++) {
      const idx = i + 3;
      const r = recentInfo[i];
      console.log(`  ${C.cyan}[${idx}]${C.reset} ${r.path}    ${markerFor(r.init)}`);
      choices.push({ kind: 'path', value: r.path });
    }
  }

  console.log('');
  const raw = (await prompt(`  Enter choice [1]: `)).trim();
  const idx = raw === '' ? 0 : parseInt(raw, 10) - 1;

  if (Number.isNaN(idx) || idx < 0 || idx >= choices.length) {
    console.log(`  ${C.yellow}Invalid choice. Exiting.${C.reset}`);
    process.exit(1);
  }

  const chosen = choices[idx];
  if (chosen.kind === 'pick') {
    console.log(`  ${C.dim}Opening folder dialog…${C.reset}`);
    const picked = await pickFolderNative();
    if (!picked) {
      console.log(`  ${C.yellow}No folder selected. Exiting.${C.reset}`);
      process.exit(0);
    }
    return picked;
  }
  return chosen.value;
}



// ====== embedded UI HTML ======
const UI_HTML = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>code_boss</title>
<style>
  :root {
    --bg: #f6f7f9;
    --panel: #ffffff;
    --border: #e3e6eb;
    --fg: #1f2328;
    --muted: #6b7280;
    --accent: #2563eb;
    --accent-fg: #ffffff;
    --user-bubble: #2563eb;
    --asst-bubble: #ffffff;
    --error: #b91c1c;
    --error-bg: #fef2f2;
    --warn-bg: #fffbeb;
  }
  * { box-sizing: border-box; }
  html, body { height: 100%; margin: 0; }
  body {
    font: 14px/1.5 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
    color: var(--fg);
    background: var(--bg);
    display: flex;
    flex-direction: column;
  }
  #landing {
    flex: 1;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    padding: 32px 24px;
    max-width: 640px;
    margin: 0 auto;
    width: 100%;
  }
  #landing.hidden, #chat.hidden { display: none; }
  #landing h1 { font-size: 28px; margin: 0 0 6px; letter-spacing: -0.5px; }
  #landing .tagline { color: var(--muted); margin: 0 0 32px; }
  #pickBtn {
    font-size: 16px;
    font-weight: 600;
    padding: 14px 28px;
    border-radius: 8px;
  }
  #landing h2 {
    font-size: 13px;
    text-transform: uppercase;
    letter-spacing: 0.6px;
    color: var(--muted);
    margin: 40px 0 10px;
    align-self: stretch;
  }
  .recent-list { list-style: none; padding: 0; margin: 0; width: 100%; }
  .recent-item {
    background: var(--panel);
    border: 1px solid var(--border);
    border-radius: 8px;
    padding: 10px 14px;
    margin-bottom: 8px;
    cursor: pointer;
    transition: border-color 0.1s;
  }
  .recent-item:hover { border-color: var(--accent); }
  .recent-item .name { font-weight: 600; }
  .recent-item .path { color: var(--muted); font-size: 12px; font-family: ui-monospace, Menlo, Consolas, monospace; margin-top: 2px; word-break: break-all; }
  .recent-empty { color: var(--muted); font-size: 13px; text-align: center; padding: 12px; }
  .project-chip {
    background: #f1f5f9;
    padding: 4px 10px;
    border-radius: 6px;
    font-size: 12px;
    font-family: ui-monospace, Menlo, Consolas, monospace;
    color: #334155;
    max-width: 360px;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    cursor: help;
  }
  #chat { flex: 1; display: flex; flex-direction: column; min-height: 0; }

  header {
    background: var(--panel);
    border-bottom: 1px solid var(--border);
    padding: 10px 16px;
    display: flex;
    align-items: center;
    gap: 12px;
    flex-shrink: 0;
  }
  header h1 { margin: 0; font-size: 16px; font-weight: 600; letter-spacing: -0.2px; }
  header .grow { flex: 1; }
  header select, header .btn {
    font: inherit;
    padding: 6px 10px;
    border: 1px solid var(--border);
    background: #fff;
    border-radius: 6px;
    cursor: pointer;
  }
  header select { cursor: default; min-width: 200px; }
  header .btn:hover { background: #f3f4f6; }
  .chip {
    background: #eef2ff;
    color: #3730a3;
    padding: 4px 10px;
    border-radius: 999px;
    font-size: 12px;
    font-weight: 500;
    font-variant-numeric: tabular-nums;
  }

  main {
    flex: 1;
    overflow-y: auto;
    padding: 16px 16px 24px;
  }
  .log { max-width: 820px; margin: 0 auto; }
  .bubble {
    max-width: 80%;
    padding: 10px 14px;
    border-radius: 14px;
    margin: 8px 0;
    white-space: pre-wrap;
    word-wrap: break-word;
    line-height: 1.45;
  }
  .bubble.user {
    background: var(--user-bubble);
    color: #fff;
    margin-left: auto;
    border-bottom-right-radius: 4px;
  }
  .bubble.assistant {
    background: var(--asst-bubble);
    border: 1px solid var(--border);
    border-bottom-left-radius: 4px;
  }
  .bubble.system {
    background: var(--warn-bg);
    border: 1px solid #fde68a;
    color: #78350f;
    font-size: 12px;
    text-align: center;
    margin: 8px auto;
    max-width: 70%;
  }
  .bubble .meta {
    color: var(--muted);
    font-size: 11px;
    margin-top: 6px;
  }

  footer {
    background: var(--panel);
    border-top: 1px solid var(--border);
    padding: 12px 16px;
    flex-shrink: 0;
  }
  .input-row {
    max-width: 820px;
    margin: 0 auto;
    display: flex;
    gap: 8px;
    align-items: flex-end;
  }
  textarea {
    flex: 1;
    min-height: 44px;
    max-height: 200px;
    padding: 10px 12px;
    border: 1px solid var(--border);
    border-radius: 8px;
    font: inherit;
    resize: vertical;
    outline: none;
  }
  textarea:focus { border-color: var(--accent); box-shadow: 0 0 0 3px rgba(37,99,235,0.15); }
  .btn.primary {
    background: var(--accent);
    color: var(--accent-fg);
    border-color: var(--accent);
    padding: 10px 18px;
    font-weight: 600;
  }
  .btn.primary:disabled { opacity: 0.5; cursor: not-allowed; }
  .btn.primary:not(:disabled):hover { background: #1d4ed8; }

  .modal-bg {
    position: fixed; inset: 0;
    background: rgba(15,23,42,0.55);
    display: none;
    align-items: flex-start;
    justify-content: center;
    padding: 40px 16px 16px;
    overflow-y: auto;
    z-index: 100;
  }
  .modal-bg.show { display: flex; }
  .modal {
    background: var(--panel);
    border-radius: 10px;
    max-width: 720px;
    width: 100%;
    box-shadow: 0 20px 50px rgba(0,0,0,0.25);
    overflow: hidden;
  }
  .modal.error { border-top: 4px solid var(--error); }
  .modal-header {
    padding: 16px 20px;
    border-bottom: 1px solid var(--border);
    display: flex;
    align-items: center;
    justify-content: space-between;
  }
  .modal-header h2 { margin: 0; font-size: 17px; }
  .modal.error .modal-header h2 { color: var(--error); }
  .modal-body { padding: 18px 20px; max-height: 70vh; overflow-y: auto; }
  .modal-close {
    background: none;
    border: none;
    cursor: pointer;
    font-size: 20px;
    color: var(--muted);
    padding: 4px 8px;
    line-height: 1;
  }
  .modal-close:hover { color: var(--fg); }

  .kv { display: grid; grid-template-columns: 160px 1fr; gap: 6px 16px; font-size: 13px; }
  .kv .k { color: var(--muted); font-weight: 500; }
  .kv .v { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; word-break: break-all; }

  table { border-collapse: collapse; width: 100%; font-size: 12px; margin-top: 8px; }
  th, td { padding: 5px 8px; border-bottom: 1px solid var(--border); text-align: left; vertical-align: top; }
  th { background: #f3f4f6; font-weight: 600; }
  td.t-ms { font-variant-numeric: tabular-nums; color: var(--muted); width: 60px; }
  td.t-type { font-family: ui-monospace, monospace; font-size: 11px; color: var(--accent); width: 130px; }

  pre {
    background: #f6f8fa;
    border: 1px solid var(--border);
    padding: 10px 12px;
    border-radius: 6px;
    overflow-x: auto;
    font: 11px/1.45 ui-monospace, Menlo, Consolas, monospace;
    max-height: 320px;
  }
  h3 { margin: 18px 0 6px; font-size: 13px; font-weight: 600; color: var(--muted); text-transform: uppercase; letter-spacing: 0.5px; }
  .par-badge {
    display: inline-block;
    font-size: 10px;
    font-weight: 700;
    padding: 2px 8px;
    border-radius: 999px;
    letter-spacing: 0.5px;
    margin-left: 8px;
    vertical-align: middle;
  }
  .par-good { background: #d1fae5; color: #065f46; }
  .par-warn { background: #fef3c7; color: #92400e; }
  .par-bad  { background: #fee2e2; color: #991b1b; }
  .par-na   { background: #e5e7eb; color: #4b5563; }
  .par-caption { color: var(--muted); font-size: 12px; margin: 0 0 12px; }
  .batch-strip {
    display: flex;
    flex-wrap: wrap;
    gap: 4px;
    margin: 10px 0 4px;
    padding: 8px;
    background: #f6f8fa;
    border: 1px solid var(--border);
    border-radius: 6px;
  }
  .batch-strip .dot {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    min-width: 22px;
    height: 22px;
    padding: 0 6px;
    border-radius: 4px;
    font-size: 11px;
    font-weight: 600;
    font-variant-numeric: tabular-nums;
  }
  .dot-single { background: #e5e7eb; color: #6b7280; }
  .dot-multi  { background: #2563eb; color: #fff; }
  .error-banner {
    background: var(--error-bg);
    border-left: 4px solid var(--error);
    padding: 10px 14px;
    margin: 8px 0;
    border-radius: 0 6px 6px 0;
  }
  .error-banner strong { color: var(--error); }
  /* Dense, high-contrast block optimized for a single screenshot (photo of screen). */
  pre.dense {
    background: #fff;
    color: #000;
    border: 2px solid #000;
    font: bold 15px/1.4 ui-monospace, Consolas, Menlo, monospace;
    padding: 12px;
    white-space: pre-wrap;
    word-break: break-word;
    margin: 0 0 12px;
  }
  .modal.error pre.dense { border-color: var(--error); }
</style>
</head>
<body>

<div id="landing">
  <h1>code_boss</h1>
  <p class="tagline">Pick a project folder to work on.</p>
  <button class="btn primary" id="pickBtn" onclick="pickFolder()">Pick a folder…</button>
  <h2>Recent projects</h2>
  <ul class="recent-list" id="recentList"></ul>
</div>

<div id="chat" class="hidden">
  <header>
    <h1>code_boss</h1>
    <span class="project-chip" id="projectChip" title="" onclick="changeProject()">📁 (no project)</span>
    <select id="model" title="Model"></select>
    <div class="grow"></div>
    <div class="chip" id="tokenChip" title="Total tokens this session">0 tokens</div>
    <button class="btn" onclick="openSnapshot()">Snapshot</button>
    <button class="btn" onclick="resetSession()">Reset</button>
    <button class="btn" onclick="changeProject()" title="Pick a different project">Change project</button>
  </header>

  <main id="logScroll">
    <div class="log" id="log">
      <div class="bubble system">Type a question and press Enter (Shift+Enter for newline).</div>
    </div>
  </main>

  <footer>
    <div class="input-row">
      <textarea id="input" placeholder="Ask…"></textarea>
      <button class="btn primary" id="sendBtn" onclick="send()">Send</button>
    </div>
  </footer>
</div>

<div class="modal-bg" id="modalBg" onclick="if (event.target === this) closeModal()">
  <div class="modal" id="modal">
    <div class="modal-header">
      <h2 id="modalTitle">Snapshot</h2>
      <button class="modal-close" onclick="closeModal()">&times;</button>
    </div>
    <div class="modal-body" id="modalBody"></div>
  </div>
</div>

<script>
  const $landing = document.getElementById('landing');
  const $chat = document.getElementById('chat');
  const $pickBtn = document.getElementById('pickBtn');
  const $recentList = document.getElementById('recentList');
  const $projectChip = document.getElementById('projectChip');
  const $log = document.getElementById('log');
  const $logScroll = document.getElementById('logScroll');
  const $input = document.getElementById('input');
  const $send = document.getElementById('sendBtn');
  const $model = document.getElementById('model');
  const $tokenChip = document.getElementById('tokenChip');
  const $modalBg = document.getElementById('modalBg');
  const $modal = document.getElementById('modal');
  const $modalTitle = document.getElementById('modalTitle');
  const $modalBody = document.getElementById('modalBody');

  const SERVER = window.SERVER_CONFIG || {};
  let conversation = [];
  let totalTokens = 0;
  let activeProject = null;

  function basename(p) {
    if (!p) return '';
    return p.split(/[\\\\/]/).filter(Boolean).pop() || p;
  }

  async function loadState() {
    try {
      const r = await fetch('/api/state');
      const s = await r.json();
      if (s.activeProject) {
        showChat(s.activeProject);
      } else {
        showLanding(s.recent ?? []);
      }
    } catch (e) {
      showError('Failed to load state', e);
    }
  }

  function showLanding(recent) {
    activeProject = null;
    $chat.classList.add('hidden');
    $landing.classList.remove('hidden');
    $recentList.innerHTML = '';
    if (!recent || recent.length === 0) {
      $recentList.innerHTML = '<li class="recent-empty">No recent projects yet.</li>';
      return;
    }
    for (const p of recent) {
      const li = document.createElement('li');
      li.className = 'recent-item';
      li.innerHTML = '<div class="name">' + escapeHtml(basename(p)) + '</div>'
        + '<div class="path">' + escapeHtml(p) + '</div>';
      li.addEventListener('click', () => openProject(p));
      $recentList.appendChild(li);
    }
  }

  function showChat(projectPath) {
    activeProject = projectPath;
    $landing.classList.add('hidden');
    $chat.classList.remove('hidden');
    $projectChip.textContent = '📁 ' + basename(projectPath);
    $projectChip.title = projectPath;
    // Fresh chat on project switch
    conversation = [];
    totalTokens = 0;
    $tokenChip.textContent = '0 tokens';
    $log.innerHTML = '<div class="bubble system">Working in ' + escapeHtml(projectPath) + '</div>';
    if ($model.options.length === 0 || $model.value === '') loadModels();
    $input.focus();
  }

  async function pickFolder() {
    $pickBtn.disabled = true;
    $pickBtn.textContent = 'Choose folder in dialog…';
    try {
      const r = await fetch('/api/pick-folder', { method: 'POST' });
      const data = await r.json();
      if (data.path) {
        await openProject(data.path);
      }
    } catch (e) {
      showError('Folder picker failed', e);
    } finally {
      $pickBtn.disabled = false;
      $pickBtn.textContent = 'Pick a folder…';
    }
  }

  async function openProject(p) {
    try {
      const r = await fetch('/api/open-project', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ path: p }),
      });
      if (!r.ok) {
        const data = await r.json();
        throw new Error(data.error ?? ('HTTP ' + r.status));
      }
      showChat(p);
    } catch (e) {
      showError('Could not open project', e);
    }
  }

  async function changeProject() {
    if (!confirm('Switch projects? This will clear the current chat.')) return;
    try { await fetch('/api/close-project', { method: 'POST' }); } catch {}
    const r = await fetch('/api/state');
    const s = await r.json();
    showLanding(s.recent ?? []);
  }

  function escapeHtml(s) {
    if (s == null) return '';
    return String(s).replace(/[&<>"']/g, (c) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  }

  function addBubble(role, text) {
    const div = document.createElement('div');
    div.className = 'bubble ' + role;
    div.textContent = text;
    $log.appendChild(div);
    scrollToBottom();
    return div;
  }
  function scrollToBottom() {
    $logScroll.scrollTop = $logScroll.scrollHeight;
  }

  async function loadModels() {
    try {
      const r = await fetch('/api/models');
      if (!r.ok) {
        const body = await r.text();
        throw new Error('GET /api/models failed: ' + r.status + ' ' + body.slice(0, 300));
      }
      const data = await r.json();
      const list = Array.isArray(data?.data) ? data.data : Array.isArray(data) ? data : [];
      $model.innerHTML = '';
      if (list.length === 0) {
        $model.innerHTML = '<option>(no models)</option>';
        return;
      }
      for (const m of list) {
        const id = m.id ?? m.name ?? String(m);
        const opt = document.createElement('option');
        opt.value = id;
        opt.textContent = id;
        if (id === SERVER.defaultModel) opt.selected = true;
        $model.appendChild(opt);
      }
    } catch (e) {
      $model.innerHTML = '<option>(load failed)</option>';
      showError('Failed to load models', e);
    }
  }

  async function send() {
    const text = $input.value.trim();
    if (!text) return;
    $input.value = '';
    $input.disabled = true;
    $send.disabled = true;

    addBubble('user', text);
    conversation.push({ role: 'user', content: text });
    const asst = addBubble('assistant', '…');

    let accumulated = '';
    try {
      const res = await fetch('/api/chat', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ model: $model.value, messages: conversation }),
      });
      if (!res.ok) {
        const body = await res.text();
        throw new Error('HTTP ' + res.status + ' — ' + body.slice(0, 400));
      }
      const reader = res.body.getReader();
      const dec = new TextDecoder();
      let buf = '';
      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        buf += dec.decode(value, { stream: true });
        let idx;
        while ((idx = buf.indexOf('\\n')) !== -1) {
          const line = buf.slice(0, idx).replace(/\\r$/, '');
          buf = buf.slice(idx + 1);
          if (!line.startsWith('data:')) continue;
          const data = line.slice(5).trim();
          if (data === '[DONE]') continue;
          try {
            const chunk = JSON.parse(data);
            const d = chunk.choices?.[0]?.delta ?? {};
            if (d.content) {
              if (accumulated === '') asst.textContent = '';
              accumulated += d.content;
              asst.textContent = accumulated;
              scrollToBottom();
            }
            if (chunk.usage) {
              totalTokens += chunk.usage.total_tokens ?? 0;
              $tokenChip.textContent = totalTokens.toLocaleString() + ' tokens';
            }
            if (chunk.error) throw new Error(chunk.error.message ?? JSON.stringify(chunk.error));
          } catch (parseErr) {
            // ignore malformed line
          }
        }
      }
      if (!accumulated) asst.textContent = '(no content)';
      conversation.push({ role: 'assistant', content: accumulated });
    } catch (e) {
      asst.remove();
      conversation.pop(); // remove the user message that wasn't completed
      showError('Chat request failed', e);
    } finally {
      $input.disabled = false;
      $send.disabled = false;
      $input.focus();
    }
  }

  async function openSnapshot() {
    try {
      const r = await fetch('/api/snapshot');
      if (!r.ok) throw new Error('snapshot fetch failed: ' + r.status);
      const data = await r.json();
      renderSnapshot(data);
    } catch (e) {
      showError('Snapshot fetch failed', e);
    }
  }

  function renderSnapshot(d) {
    $modal.classList.remove('error');
    $modalTitle.textContent = 'Snapshot';
    const events = d.events ?? [];
    const lastTx = [...events].reverse().find((e) => e.type === 'chat_completions' || e.type === 'list_models');
    const rows = events.map((e) =>
      '<tr><td class="t-ms">' + e.at + '</td><td class="t-type">' + escapeHtml(e.type) + '</td><td>' + escapeHtml(e.summary) + '</td></tr>'
    ).join('');
    const p = d.parallelism ?? {};
    const batches = Array.isArray(p.batches) ? p.batches : [];
    let parallelismBadge = '';
    let parallelismCaption = '';
    if (p.turnsWithTools === 0) {
      parallelismBadge = '<span class="par-badge par-na">no tool turns yet</span>';
      parallelismCaption = 'Ask a question that needs the agent to use tools to populate this.';
    } else if (p.maxParallel <= 1) {
      parallelismBadge = '<span class="par-badge par-bad">SEQUENTIAL ONLY</span>';
      parallelismCaption = 'Every turn issued exactly one tool call. The model is not batching parallel calls.';
    } else if ((p.multiCallTurns / p.turnsWithTools) < 0.25) {
      parallelismBadge = '<span class="par-badge par-warn">RARE</span>';
      parallelismCaption = 'Most turns still issue one call at a time.';
    } else {
      parallelismBadge = '<span class="par-badge par-good">BATCHING</span>';
      parallelismCaption = 'Model is emitting parallel tool calls in some turns.';
    }
    const batchDots = batches.map((n) => {
      const cls = n > 1 ? 'dot dot-multi' : 'dot dot-single';
      return '<span class="' + cls + '" title="turn with ' + n + ' tool call(s)">' + n + '</span>';
    }).join('');
    // Dense one-screenshot summary at the very top.
    const lastFinish = lastTx?.response?.choices?.[0]?.finish_reason ?? '?';
    const lastTools = lastTx?.response?.choices?.[0]?.message?.tool_calls ? 'yes' : 'no';
    const dense = [
      '== snapshot ' + new Date().toISOString().slice(0, 19) + 'Z ==',
      'proj   ' + (d.activeProject ?? '(none)'),
      'base   ' + (d.baseURL ?? '?'),
      'model  ' + (d.defaultModel ?? '?') + '   key ' + (d.apiKeyPrefix ?? '?'),
      'tokens ' + (d.totalTokens ?? 0) + '   events ' + events.length,
      'parallel runs=' + (p.runs ?? 0) + ' turns=' + (p.turnsWithTools ?? 0) +
        ' calls=' + (p.totalToolCalls ?? 0) + ' max=' + (p.maxParallel ?? 0) +
        ' batches=[' + batches.join(',') + ']',
      'lastTx ' + (lastTx ? (lastTx.type + ' finish=' + lastFinish + ' tool_calls=' + lastTools) : '(none)'),
    ].join('\\n');
    $modalBody.innerHTML = [
      '<pre class="dense">' + escapeHtml(dense) + '</pre>',
      '<div class="kv">',
      '<div class="k">Started</div><div class="v">' + escapeHtml(d.startedAt) + '</div>',
      '<div class="k">Active project</div><div class="v">' + escapeHtml(d.activeProject ?? '(none)') + '</div>',
      '<div class="k">Base URL</div><div class="v">' + escapeHtml(d.baseURL) + '</div>',
      '<div class="k">Default model</div><div class="v">' + escapeHtml(d.defaultModel) + '</div>',
      '<div class="k">API key prefix</div><div class="v">' + escapeHtml(d.apiKeyPrefix) + '</div>',
      '<div class="k">Events</div><div class="v">' + events.length + '</div>',
      '<div class="k">Total tokens</div><div class="v">' + (d.totalTokens ?? 0) + '</div>',
      '</div>',
      '<h3>Parallel tool batching ' + parallelismBadge + '</h3>',
      '<p class="par-caption">' + escapeHtml(parallelismCaption) + '</p>',
      '<div class="kv">',
      '<div class="k">Agent runs</div><div class="v">' + (p.runs ?? 0) + '</div>',
      '<div class="k">Turns with tools</div><div class="v">' + (p.turnsWithTools ?? 0) + '</div>',
      '<div class="k">Total tool calls</div><div class="v">' + (p.totalToolCalls ?? 0) + '</div>',
      '<div class="k">Avg per turn</div><div class="v">' + (p.avgPerTurn ?? 0) + '</div>',
      '<div class="k">Max parallel</div><div class="v">' + (p.maxParallel ?? 0) + ' call(s) in one turn</div>',
      '<div class="k">Single-call turns</div><div class="v">' + (p.singleCallTurns ?? 0) + '</div>',
      '<div class="k">Multi-call turns</div><div class="v">' + (p.multiCallTurns ?? 0) + '</div>',
      '</div>',
      batches.length ? '<div class="batch-strip">' + batchDots + '</div>' : '',
      '<h3>Events</h3>',
      events.length
        ? '<table><thead><tr><th>+ms</th><th>type</th><th>summary</th></tr></thead><tbody>' + rows + '</tbody></table>'
        : '<p style="color:var(--muted)">No events yet.</p>',
      lastTx ? '<h3>Last transaction</h3>' : '',
      lastTx && lastTx.request != null ? '<h4 style="margin:8px 0 4px;font-size:12px">Request</h4><pre>' + escapeHtml(JSON.stringify(lastTx.request, null, 2)).slice(0, 8000) + '</pre>' : '',
      lastTx && lastTx.response != null ? '<h4 style="margin:8px 0 4px;font-size:12px">Response</h4><pre>' + escapeHtml(JSON.stringify(lastTx.response, null, 2)).slice(0, 12000) + '</pre>' : '',
    ].join('');
    $modalBg.classList.add('show');
  }

  function showError(title, err) {
    $modal.classList.add('error');
    $modalTitle.textContent = title;
    const message = err?.message ?? String(err);
    const stack = (err?.stack ?? '').split('\\n').slice(0, 6).join('\\n');
    const dense = [
      'ERR   ' + title,
      'msg   ' + message,
      'proj  ' + (activeProject || '(none)'),
      'model ' + ($model.value || SERVER.defaultModel || '?'),
      'tok   ' + totalTokens,
      'time  ' + new Date().toISOString().slice(0, 19) + 'Z',
      stack ? 'stack ' + stack.replace(/\\n/g, '\\n      ') : '',
    ].filter(Boolean).join('\\n');
    $modalBody.innerHTML = '<pre class="dense">' + escapeHtml(dense) + '</pre>';
    $modalBg.classList.add('show');
  }

  function closeModal() { $modalBg.classList.remove('show'); }

  async function resetSession() {
    if (!confirm('Clear the chat and reset the snapshot log?')) return;
    conversation = [];
    totalTokens = 0;
    $tokenChip.textContent = '0 tokens';
    $log.innerHTML = '<div class="bubble system">Session reset.</div>';
    try { await fetch('/api/reset', { method: 'POST' }); } catch {}
  }

  $input.addEventListener('keydown', (e) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      send();
    }
  });
  document.addEventListener('keydown', (e) => {
    if (e.key === 'Escape') closeModal();
  });

  loadState();
</script>
</body>
</html>
`;

function openInDefaultBrowser(url) {
  // Prefer Chrome; fall back to the OS default if Chrome isn't installed.
  if (process.platform === 'win32') {
    const candidates = [
      (process.env.LOCALAPPDATA || '') + '\\Google\\Chrome\\Application\\chrome.exe',
      'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',
      'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe',
    ];
    const chrome = candidates.find((p) => { try { return p && existsSync(p); } catch { return false; } });
    if (chrome) spawn(chrome, [url], { stdio: 'ignore', detached: true }).unref();
    else spawn('cmd', ['/c', 'start', '""', url], { stdio: 'ignore', detached: true, windowsHide: true }).unref();
  } else if (process.platform === 'darwin') {
    spawn('open', ['-a', 'Google Chrome', url], { stdio: 'ignore', detached: true }).unref();
  } else {
    spawn('google-chrome', [url], { stdio: 'ignore', detached: true })
      .on('error', () => spawn('xdg-open', [url], { stdio: 'ignore', detached: true }).unref())
      .unref();
  }
}

// startServer was inlined above (from server.mjs). Wire defaults from CONFIG.
const htmlWithConfig = UI_HTML.replace(
  '</head>',
  '<script>window.SERVER_CONFIG=' + JSON.stringify({ defaultModel: MODEL, baseURL: BASE_URL }) + ';</script></head>'
);

(async () => {
  try {
    const recent = await loadRecentProjects();
    const initialProject = await selectProject({ recent });
    console.error('[code_boss] active project: ' + initialProject);

    const { port } = await startServer({
      html: htmlWithConfig,
      baseURL: BASE_URL,
      apiKey: API_KEY,
      defaultModel: MODEL,
      port: PORT,
      initialProject,
    });
    const url = 'http://127.0.0.1:' + port + '/';
    console.error('[code_boss] listening on ' + url);
    console.error('[code_boss] base URL: ' + BASE_URL);
    console.error('[code_boss] model:    ' + MODEL);
    if (process.env.OPEN_BROWSER !== '0') {
      openInDefaultBrowser(url);
      console.error('[code_boss] opening browser; press Ctrl+C to stop.');
    } else {
      console.error('[code_boss] OPEN_BROWSER=0 — not opening a browser. Visit ' + url + ' manually.');
    }
  } catch (e) {
    console.error('[code_boss] FAILED TO START:', e.message);
    if (e.code === 'EADDRINUSE') {
      console.error('  Port ' + PORT + ' is already in use. Set PORT=<other> and rerun.');
    }
    process.exit(1);
  }
})();
