#!/usr/bin/env node
/**
 * code_boss — production single-file bundle. Generated by scripts/build.mjs.
 * Talks to an OpenAI-compatible HTTP endpoint (api.genai.mil by default).
 * No npm deps. Node 20+ for built-in fetch.
 *
 * Usage:
 *   node code-boss.mjs "What is the capital of Japan?"
 *   AGENT_STREAM=1 node code-boss.mjs "Name three primary colors."
 *
 * Edit the CONFIG constants below for your environment.
 */

// ====== CONFIG (edit these) ======
const API_KEY  = '';                                // bearer token
const BASE_URL = 'https://api.genai.mil/v1';        // OpenAI-compatible endpoint
const MODEL    = '';                                // leave blank to auto-pick first from /models
// ==================================

import { spawn } from 'node:child_process';
import { createInterface } from 'node:readline';


// ====== llm/openai-http.mjs ======
/**
 * Production OpenAI-compatible HTTP adapter — talks to api.genai.mil.
 *
 * Same surface as the dev adapter:
 *   const a = createHttpAdapter({ baseURL, apiKey })
 *   await a.complete(openaiRequest)
 *   for await (const chunk of a.completeStream(openaiRequest)) { ... }
 *
 * Production behaviours wired in here:
 *   - 401 with `unlock_url` → open the URL in the default browser, prompt the
 *     user to press Enter once they've unlocked in the browser, then retry
 *     once. The /user-ui/unlock/... endpoints are browser pages, not API
 *     endpoints — programmatic GET doesn't actually unlock the key.
 *   - 429 with Retry-After header or retry_after_seconds body → sleep, retry
 *     (max 3 attempts, exponential floor)
 *   - SSE streaming parsed into OpenAI ChatCompletionChunk async iterator
 *   - Bearer auth via Authorization header
 *
 * No npm deps. Node 18+ built-in fetch only.
 */


const DEFAULT_BASE_URL = 'https://api.genai.mil/v1';

function openInBrowser(url) {
  // Windows: `start "" "<url>"` via cmd. macOS: open. Linux: xdg-open.
  // We're targeting Windows by default; the others are a courtesy.
  if (process.platform === 'win32') {
    spawn('cmd', ['/c', 'start', '""', url], { stdio: 'ignore', detached: true, windowsHide: true }).unref();
  } else if (process.platform === 'darwin') {
    spawn('open', [url], { stdio: 'ignore', detached: true }).unref();
  } else {
    spawn('xdg-open', [url], { stdio: 'ignore', detached: true }).unref();
  }
}

function promptEnter(message) {
  return new Promise((resolve) => {
    const rl = createInterface({ input: process.stdin, output: process.stderr });
    rl.question(message, () => { rl.close(); resolve(); });
  });
}

class HttpError extends Error {
  constructor(status, statusText, body) {
    super(`HTTP ${status} ${statusText}: ${typeof body === 'string' ? body.slice(0, 500) : JSON.stringify(body).slice(0, 500)}`);
    this.status = status;
    this.statusText = statusText;
    this.body = body;
  }
}

function sleep(ms) {
  return new Promise((r) => setTimeout(r, ms));
}

function parseRetryAfter(headers, body) {
  const headerVal = headers.get?.('retry-after');
  const headerSec = headerVal ? Number(headerVal) : NaN;
  const bodySec = Number(body?.retry_after_seconds);
  const candidates = [headerSec, bodySec].filter((n) => Number.isFinite(n) && n > 0);
  if (candidates.length === 0) return 1;
  return Math.max(...candidates);
}

async function readJson(res) {
  const text = await res.text();
  try {
    return JSON.parse(text);
  } catch {
    return { raw: text };
  }
}

/**
 * @param {object} opts
 * @param {string} [opts.baseURL]     Defaults to https://api.genai.mil/v1
 * @param {string} [opts.apiKey]      Bearer token. Defaults to process.env.AGENT_API_KEY.
 * @param {Function} [opts.fetchImpl] Override for tests (default: globalThis.fetch).
 * @param {number}   [opts.maxRetries] Default 3.
 * @param {Function} [opts.onUnlock]   Callback(url) when an unlock is performed (telemetry).
 * @param {Function} [opts.onRateLimit] Callback(ms) when a 429 sleep happens (telemetry).
 * @param {Function} [opts.onUsage]    Callback(usage) on successful response.
 */
function createHttpAdapter(opts = {}) {
  const baseURL = (opts.baseURL ?? process.env.AGENT_BASE_URL ?? DEFAULT_BASE_URL).replace(/\/+$/, '');
  const apiKey = opts.apiKey ?? process.env.AGENT_API_KEY ?? '';
  const fetchImpl = opts.fetchImpl ?? globalThis.fetch;
  const maxRetries = opts.maxRetries ?? 3;
  const onUnlock = opts.onUnlock ?? (() => {});
  const onRateLimit = opts.onRateLimit ?? (() => {});
  const onUsage = opts.onUsage ?? (() => {});

  if (!fetchImpl) throw new Error('createHttpAdapter: no fetch implementation available');

  async function doFetchOnce(path, init) {
    const url = `${baseURL}${path}`;
    const headers = {
      'content-type': 'application/json',
      accept: init?.body && JSON.parse(init.body).stream ? 'text/event-stream' : 'application/json',
      ...(apiKey ? { authorization: `Bearer ${apiKey}` } : {}),
      ...(init?.headers ?? {}),
    };
    return fetchImpl(url, { ...init, headers });
  }

  async function safeFetch(path, init) {
    let attempt = 0;
    let unlocked = false;
    while (true) {
      const res = await doFetchOnce(path, init);
      if (res.ok) return res;

      if (res.status === 401 && !unlocked) {
        const body = await readJson(res);
        const unlockUrl = body?.unlock_url ?? body?.error?.unlock_url;
        if (unlockUrl) {
          onUnlock(unlockUrl);
          if (opts.openBrowser !== false) openInBrowser(unlockUrl);
          await promptEnter(`\n[unlock] API key is locked. A browser tab should have opened:\n  ${unlockUrl}\nUnlock the key in your browser, then press Enter to retry... `);
          unlocked = true;
          continue;
        }
        throw new HttpError(res.status, res.statusText, body);
      }

      if (res.status === 429 && attempt < maxRetries) {
        const body = await readJson(res);
        const waitSec = parseRetryAfter(res.headers, body);
        const waitMs = Math.max(waitSec * 1000, 500 * Math.pow(2, attempt));
        onRateLimit(waitMs);
        await sleep(waitMs);
        attempt++;
        continue;
      }

      const body = await readJson(res);
      throw new HttpError(res.status, res.statusText, body);
    }
  }

  async function complete(request) {
    if (!request || !Array.isArray(request.messages)) {
      throw new TypeError('complete: request.messages is required');
    }
    const res = await safeFetch('/chat/completions', {
      method: 'POST',
      body: JSON.stringify({ ...request, stream: false }),
    });
    const json = await res.json();
    if (json.usage) onUsage(json.usage);
    return json;
  }

  async function* completeStream(request) {
    if (!request || !Array.isArray(request.messages)) {
      throw new TypeError('completeStream: request.messages is required');
    }
    const res = await safeFetch('/chat/completions', {
      method: 'POST',
      body: JSON.stringify({ ...request, stream: true }),
    });

    if (!res.body) throw new Error('completeStream: response has no body');

    const reader = res.body.getReader();
    const decoder = new TextDecoder();
    let buf = '';
    let usageFired = false;
    const fireUsageOnce = (u) => {
      if (u && !usageFired) {
        usageFired = true;
        onUsage(u);
      }
    };

    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      buf += decoder.decode(value, { stream: true });

      let idx;
      while ((idx = buf.indexOf('\n')) !== -1) {
        const line = buf.slice(0, idx).replace(/\r$/, '');
        buf = buf.slice(idx + 1);
        if (!line || line.startsWith(':')) continue;
        if (!line.startsWith('data:')) continue;
        const data = line.slice(5).trim();
        if (data === '[DONE]') return;
        try {
          const chunk = JSON.parse(data);
          fireUsageOnce(chunk.usage);
          yield chunk;
        } catch {
          // ignore malformed line
        }
      }
    }
  }

  async function listModels() {
    const res = await safeFetch('/models', { method: 'GET' });
    return res.json();
  }

  return { complete, completeStream, listModels };
}



// ====== main ======
async function __main() {
  const question = process.argv.slice(2).join(' ').trim()
    || 'What is the capital of Japan?';
  const useStream = process.env.AGENT_STREAM === '1';

  const adapter = createHttpAdapter({
    baseURL: BASE_URL,
    apiKey: API_KEY,
    onUnlock: (url) => console.error(`[unlock] hit ${url}`),
    onRateLimit: (ms) => console.error(`[rate-limit] sleeping ${ms}ms`),
    onUsage: (u) => console.error(`[usage] ${JSON.stringify(u)}`),
  });

  let modelToUse = MODEL;
  if (!modelToUse) {
    console.error('[models] fetching list from ' + BASE_URL + '/models ...');
    const models = await adapter.listModels();
    console.error('[models] response:');
    console.error(JSON.stringify(models, null, 2));
    const list = Array.isArray(models?.data) ? models.data
                : Array.isArray(models) ? models
                : [];
    if (!list.length) throw new Error('models endpoint returned no entries');
    modelToUse = list[0].id ?? list[0].name ?? list[0];
    console.error('[models] picked first: ' + modelToUse);
  }

  console.error(`[stream=${useStream} model=${modelToUse}] Q: ${question}`);
  const request = {
    model: modelToUse,
    messages: [
      { role: 'system', content: 'Answer concisely.' },
      { role: 'user', content: question },
    ],
  };

  const t0 = Date.now();
  if (useStream) {
    let finish = null;
    for await (const chunk of adapter.completeStream(request)) {
      const d = chunk.choices?.[0]?.delta ?? {};
      if (d.content) process.stdout.write(d.content);
      if (chunk.choices?.[0]?.finish_reason) finish = chunk.choices[0].finish_reason;
    }
    process.stdout.write('\n');
    console.error(`[done] wallMs=${Date.now() - t0} finish=${finish}`);
  } else {
    const res = await adapter.complete(request);
    const content = res.choices?.[0]?.message?.content ?? '';
    process.stdout.write(content + '\n');
    console.error(`[done] wallMs=${Date.now() - t0} finish=${res.choices?.[0]?.finish_reason} usage=${JSON.stringify(res.usage ?? {})}`);
  }
}

__main().catch((e) => { console.error('FAIL:', e); process.exit(1); });
